#!/usr/bin/env python3
"""
Email Sender Module - Send HTML digest via SMTP
邮件发送模块：SMTP 认证 + HTML 富文本 + 多收件人 + 附件支持
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import List, Dict, Optional


class EmailSender:
    """SMTP email sender with HTML support"""

    def __init__(self, server: str = None, port: int = None,
                 user: str = None, password: str = None,
                 receivers: List[str] = None):
        self.server = server or os.environ.get("SMTP_SERVER", "")
        self.port = int(port or os.environ.get("SMTP_PORT", "25"))
        self.user = user or os.environ.get("SMTP_USER", "")
        self.password = password or os.environ.get("SMTP_PASSWORD", "")
        receivers_str = os.environ.get("EMAIL_RECEIVER", "")
        self.receivers = receivers or [r.strip() for r in receivers_str.split(",") if r.strip()]
        self.enabled = all([self.server, self.user, self.password, self.receivers])

    def _build_html(self, content: str, title: str = "Literature Digest") -> str:
        """Build HTML email body from markdown content"""
        # Convert markdown to HTML (basic)
        html = content
        html = html.replace("# ", "<h1>")
        html = html.replace("## ", "<h2>")
        html = html.replace("### ", "<h3>")
        html = html.replace("**", "<b>")
        html = html.replace("---", "<hr>")
        html = html.replace("\n", "<br>")

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
h2 {{ color: #34495e; margin-top: 30px; font-size: 1.2em; }}
h3 {{ color: #555; margin-top: 20px; font-size: 1.05em; }}
hr {{ border: none; border-top: 1px solid #ecf0f1; margin: 20px 0; }}
b {{ color: #2c3e50; }}
.footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1;
           color: #95a5a6; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
{html}
<div class="footer">
<p>Generated by Bio Daily Paper Digest</p>
<p><a href="https://github.com/guoqunfei/bio-daily-paper-digest">View Repository</a></p>
</div>
</body>
</html>"""

    def send(self, content_path: str, subject: str = None,
             attachments: List[str] = None) -> bool:
        """Send email with digest content"""
        if not self.enabled:
            print("[EmailSender] SMTP configuration incomplete. Skipping email.")
            return False

        attachments = attachments or []
        today = datetime.now().strftime("%Y-%m-%d")
        subject = subject or f"[Bio-Digest] {today} Literature Digest"

        # Read content
        with open(content_path, "r", encoding="utf-8") as f:
            md_content = f.read()

        # Build message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.user
        msg["To"] = ", ".join(self.receivers)

        # HTML part
        html_body = self._build_html(md_content)
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        # Attachments
        for filepath in attachments:
            if os.path.exists(filepath):
                try:
                    with open(filepath, "rb") as f:
                        part = MIMEBase("application", "octet-stream")
                        part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={os.path.basename(filepath)}"
                    )
                    msg.attach(part)
                except Exception as e:
                    print(f"[EmailSender] Failed to attach {filepath}: {e}")

        # Send
        try:
            if self.port == 465:
                server = smtplib.SMTP_SSL(self.server, self.port, timeout=30)
            else:
                server = smtplib.SMTP(self.server, self.port, timeout=30)
                if self.port != 25:
                    server.starttls()
            server.login(self.user, self.password)
            server.sendmail(self.user, self.receivers, msg.as_string())
            server.quit()
            print(f"[EmailSender] Sent to: {', '.join(self.receivers)}")
            return True
        except Exception as e:
            print(f"[EmailSender] Failed: {e}")
            return False

    def send_digest(self, digest_path: str, paper_count: int) -> bool:
        """Convenience method for sending daily digest"""
        today = datetime.now().strftime("%Y-%m-%d")
        subject = f"[Bio-Digest] {today} Literature Digest ({paper_count} papers)"
        return self.send(digest_path, subject=subject)


def get_sender() -> EmailSender:
    """Factory function"""
    return EmailSender()
