#!/usr/bin/env python3
"""
GitHub Feedback Module - Interactive feedback via GitHub Issues
交互式反馈：通过 GitHub Issue 收集用户对每篇论文的反馈
"""

import os
import requests
from datetime import datetime, timedelta
from typing import Dict, List, Optional


class GitHubFeedback:
    """Interactive GitHub Issues for user feedback and preference learning"""

    def __init__(self, token: str = None, repo: str = None):
        self.token = token or os.environ.get("GITHUB_TOKEN", "")
        self.repo = repo or os.environ.get("GITHUB_REPO", "")
        self.api_base = "https://api.github.com"
        self.enabled = bool(self.token and self.repo)

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }

    def _api_url(self, endpoint: str) -> str:
        return f"{self.api_base}/repos/{self.repo}/{endpoint}"

    def create_issue(self, title: str, body: str, labels: list = None) -> Optional[str]:
        """Create a GitHub Issue"""
        if not self.enabled:
            print("[GitHubFeedback] Disabled (missing token or repo)")
            return None

        labels = labels or ["automated"]
        payload = {
            "title": title,
            "body": body,
            "labels": labels
        }

        try:
            resp = requests.post(
                self._api_url("issues"),
                headers=self._headers(),
                json=payload,
                timeout=30
            )
            resp.raise_for_status()
            issue_url = resp.json().get("html_url", "")
            print(f"[GitHubFeedback] Issue created: {issue_url}")
            return issue_url
        except Exception as e:
            print(f"[GitHubFeedback] Failed to create issue: {e}")
            return None

    def _format_paper_for_issue(self, paper: dict, index: int) -> str:
        """Format a single paper for issue body"""
        score = paper.get("relevance_score", 0)
        score_level = paper.get("relevance_level", "参考")
        
        return f"""### {index}. {paper.get('title', 'N/A')[:80]}...
- **Source:** {paper.get('source', 'N/A')} | **Published:** {paper.get('published', 'N/A')}
- **Authors:** {paper.get('authors', 'N/A')[:60]}
- **Score:** {score}/10 ({score_level}) | **Reason:** {paper.get('relevance_reason', 'N/A')[:50]}
- **URL:** {paper.get('url', 'N/A')}

"""

    def report_success(self, paper_count: int, sources: Dict[str, int], 
                       papers: List[dict] = None, follow_ups: List[dict] = None) -> Optional[str]:
        """Report successful daily run with interactive feedback"""
        today = datetime.now().strftime("%Y-%m-%d")
        source_lines = "\n".join([f"- {src}: {cnt}" for src, cnt in sources.items()])
        
        # Build paper list section
        paper_section = ""
        if papers:
            paper_lines = []
            for i, paper in enumerate(papers[:15], 1):
                paper_lines.append(self._format_paper_for_issue(paper, i))
            paper_section = "\n".join(paper_lines)
        
        # Build follow-up reminder section
        follow_up_section = ""
        if follow_ups:
            follow_up_lines = []
            for item in follow_ups:
                follow_up_lines.append(f"- [{item.get('title', 'N/A')[:60]}]({item.get('url', '')}) (reminder: {item.get('reminder_date', 'N/A')})")
            follow_up_section = "\n".join(follow_up_lines)
        
        body = f"""## Daily Digest Success Report

**Date:** {today}
**Total Papers:** {paper_count}

### Source Distribution
{source_lines}

---

### Today's Papers
{paper_section}

---

### Follow-up Reminders
{follow_up_section if follow_ups else "No follow-up reminders due today."}

---

## 反馈指南 / Feedback Guide

您可以通过回复此 Issue 来对论文进行反馈，系统将自动学习您的偏好：

| 反馈指令 | 格式示例 | 作用 |
|---------|---------|------|
| ⭐ 有用 | `⭐ useful 3` | 标记第3篇论文为有用 |
| 🚫 不相关 | `🚫 irrelevant 3` | 标记第3篇论文为不相关 |
| ⏰ 提醒 | `⏰ follow 3 7` | 3天后提醒精读第3篇 |
| ✅ 已读 | `✅ read 3` | 标记第3篇论文为已读 |

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[Daily Digest] {today} - {paper_count} papers fetched",
            body=body,
            labels=["automated", "daily-digest", "success", "feedback"]
        )

    def report_error(self, error_message: str, traceback: str = "") -> Optional[str]:
        """Report failed run with error details"""
        today = datetime.now().strftime("%Y-%m-%d")
        body = f"""## Daily Digest Error Report

**Date:** {today}
**Status:** Failed

### Error Message
```
{error_message}
```

### Traceback
```
{traceback}
```

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[ERROR] Daily Digest Failed - {today}",
            body=body,
            labels=["automated", "daily-digest", "error", "bug"]
        )

    def report_weekly(self, paper_count: int, top_keywords: list) -> Optional[str]:
        """Report weekly trend summary"""
        week_start = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
        week_end = datetime.now().strftime("%Y-%m-%d")
        keyword_lines = "\n".join([f"- {kw}: {cnt}" for kw, cnt in top_keywords[:10]])

        body = f"""## Weekly Trend Report

**Period:** {week_start} to {week_end}
**Total Papers:** {paper_count}

### Top Keywords
{keyword_lines}

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[Weekly Trend] {week_start} to {week_end} - {paper_count} papers",
            body=body,
            labels=["automated", "weekly-trend", "report"]
        )

    def parse_feedback_comment(self, comment_body: str) -> List[dict]:
        """Parse feedback comment and return list of feedback actions
        
        Supported formats:
        - "⭐ useful 3" -> mark paper #3 as useful
        - "🚫 irrelevant 3" -> mark paper #3 as irrelevant  
        - "⏰ follow 3 7" -> remind me in 7 days about paper #3
        - "✅ read 3" -> mark paper #3 as read
        """
        feedbacks = []
        lines = comment_body.split("\n")
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            # Parse ⭐ useful N
            if line.startswith("⭐") or line.lower().startswith("useful"):
                parts = line.split()
                for part in parts:
                    if part.isdigit():
                        feedbacks.append({"action": "useful", "paper_index": int(part)})
                        break
            
            # Parse 🚫 irrelevant N
            elif line.startswith("🚫") or line.lower().startswith("irrelevant"):
                parts = line.split()
                for part in parts:
                    if part.isdigit():
                        feedbacks.append({"action": "irrelevant", "paper_index": int(part)})
                        break
            
            # Parse ⏰ follow N [days]
            elif line.startswith("⏰") or line.lower().startswith("follow"):
                parts = line.split()
                digits = [int(p) for p in parts if p.isdigit()]
                if len(digits) >= 1:
                    paper_idx = digits[0]
                    reminder_days = digits[1] if len(digits) > 1 else 3
                    feedbacks.append({
                        "action": "follow_up",
                        "paper_index": paper_idx,
                        "reminder_days": reminder_days
                    })
            
            # Parse ✅ read N
            elif line.startswith("✅") or line.lower().startswith("read"):
                parts = line.split()
                for part in parts:
                    if part.isdigit():
                        feedbacks.append({"action": "read", "paper_index": int(part)})
                        break
        
        return feedbacks


def get_feedback() -> GitHubFeedback:
    """Factory function"""
    return GitHubFeedback()
