#!/usr/bin/env python3
"""
GitHub Feedback Module - Auto-submit GitHub Issues for run status
GitHub 反馈：自动提交 Issue 汇报运行状态、错误报告
"""

import os
import requests
from datetime import datetime, timedelta
from typing import Dict, Optional


class GitHubFeedback:
    """Auto-submit GitHub Issues for feedback and error reporting"""

    def __init__(self, token: str = None, repo: str = None):
        self.token = token or os.environ.get("GITHUB_TOKEN", "")
        self.repo = repo or os.environ.get("GITHUB_REPO", "")
        self.api_base = "https://api.github.com"
        self.enabled = bool(self.token and self.repo)

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }

    def _api_url(self, endpoint: str) -> str:
        return f"{self.api_base}/repos/{self.repo}/{endpoint}"

    def create_issue(self, title: str, body: str, labels: list = None) -> Optional[str]:
        """Create a GitHub Issue"""
        if not self.enabled:
            print("[GitHubFeedback] Disabled (missing token or repo)")
            return None

        labels = labels or ["automated"]
        payload = {
            "title": title,
            "body": body,
            "labels": labels
        }

        try:
            resp = requests.post(
                self._api_url("issues"),
                headers=self._headers(),
                json=payload,
                timeout=30
            )
            resp.raise_for_status()
            issue_url = resp.json().get("html_url", "")
            print(f"[GitHubFeedback] Issue created: {issue_url}")
            return issue_url
        except Exception as e:
            print(f"[GitHubFeedback] Failed to create issue: {e}")
            return None

    def report_success(self, paper_count: int, sources: Dict[str, int]) -> Optional[str]:
        """Report successful daily run"""
        today = datetime.now().strftime("%Y-%m-%d")
        source_lines = "\n".join([f"- {src}: {cnt}" for src, cnt in sources.items()])

        body = f"""## Daily Digest Success Report

**Date:** {today}
**Total Papers:** {paper_count}

### Source Distribution
{source_lines}

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[Daily Digest] {today} - {paper_count} papers fetched",
            body=body,
            labels=["automated", "daily-digest", "success"]
        )

    def report_error(self, error_message: str, traceback: str = "") -> Optional[str]:
        """Report failed run with error details"""
        today = datetime.now().strftime("%Y-%m-%d")
        body = f"""## Daily Digest Error Report

**Date:** {today}
**Status:** Failed

### Error Message
```
{error_message}
```

### Traceback
```
{traceback}
```

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[ERROR] Daily Digest Failed - {today}",
            body=body,
            labels=["automated", "daily-digest", "error", "bug"]
        )

    def report_weekly(self, paper_count: int, top_keywords: list) -> Optional[str]:
        """Report weekly trend summary"""
        week_start = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
        week_end = datetime.now().strftime("%Y-%m-%d")
        keyword_lines = "\n".join([f"- {kw}: {cnt}" for kw, cnt in top_keywords[:10]])

        body = f"""## Weekly Trend Report

**Period:** {week_start} to {week_end}
**Total Papers:** {paper_count}

### Top Keywords
{keyword_lines}

---
*This issue was automatically generated by Bio Daily Paper Digest.*
"""
        return self.create_issue(
            title=f"[Weekly Trend] {week_start} to {week_end} - {paper_count} papers",
            body=body,
            labels=["automated", "weekly-trend", "report"]
        )


def get_feedback() -> GitHubFeedback:
    """Factory function"""
    return GitHubFeedback()
