#!/usr/bin/env python3
"""
Email Sending Module - Send HTML digest via SMTP
邮件发送模块 - 通过 SMTP 发送 HTML 格式综述邮件
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def send_digest_email(digest_path: str, paper_count: int) -> None:
    """Send the digest as an HTML email"""
    smtp_server = os.environ.get("SMTP_SERVER", "")
    smtp_port = int(os.environ.get("SMTP_PORT", "25"))
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_password = os.environ.get("SMTP_PASSWORD", "")
    receivers = os.environ.get("EMAIL_RECEIVER", "").split(",")

    if not all([smtp_server, smtp_user, smtp_password, receivers[0]]):
        print("[Email] SMTP configuration incomplete. Skipping email.")
        return

    today = datetime.now().strftime("%Y-%m-%d")
    subject = f"[Bio-Digest] {today} Literature Digest ({paper_count} papers)"

    with open(digest_path, "r", encoding="utf-8") as f:
        md_content = f.read()

    # Simple markdown-to-HTML conversion
    html_content = md_content.replace("\n", "<br>")
    html_content = html_content.replace("# ", "<h1>").replace("## ", "<h2>")
    html_content = html_content.replace("**", "<b>").replace("**", "</b>")

    html_body = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
h2 {{ color: #34495e; margin-top: 30px; font-size: 1.2em; }}
hr {{ border: none; border-top: 1px solid #ecf0f1; margin: 20px 0; }}
.footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ecf0f1;
           color: #95a5a6; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
{html_content}
<div class="footer">
<p>Generated by Bio Daily Paper Digest</p>
<p><a href="https://github.com/guoqunfei/bio-daily-paper-digest">View Repository</a></p>
</div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = ", ".join(receivers)
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        if smtp_port == 465:
            server = smtplib.SMTP_SSL(smtp_server, smtp_port, timeout=30)
        else:
            server = smtplib.SMTP(smtp_server, smtp_port, timeout=30)
            if smtp_port != 25:
                server.starttls()
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, receivers, msg.as_string())
        server.quit()
        print(f"[Email] Sent successfully to: {', '.join(receivers)}")
    except Exception as e:
        print(f"[Email] Failed to send: {e}")
